const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
  res.send('Summary Dashboard Backend is running');
});

// Placeholder for summarization endpoint
app.post('/api/summarize', (req, res) => {
  const { type, content } = req.body;
  console.log(`Summarizing ${type}:`, content);
  
  // Simulated summary result
  const summary = `This is a simulated summary for the provided ${type} content. In a real application, this would be generated by an AI model.`;
  
  res.json({ summary });
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
