export const defaultTasks = [
  {
    id: 'task-1',
    title: 'Prepare HCI viva slides',
    description: 'Refine the final 6 slides and add the system architecture diagram.',
    course: 'HCI 302',
    estimatedPomodoros: 3,
    nextAction: 'Finalize slide flow and rehearse the system demonstration once.',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-03-22T00:00:00.000Z',
  },
  {
    id: 'task-2',
    title: 'Read database normalization chapter',
    description: 'Review 1NF to BCNF examples before the quiz.',
    course: 'CS 214',
    estimatedPomodoros: 2,
    nextAction: 'Summarize each form in one page with one worked example.',
    priority: 'Medium',
    status: 'Pending',
    dueDate: '2026-03-21T00:00:00.000Z',
  },
  {
    id: 'task-3',
    title: 'Submit mobile UX reflection',
    description: 'Upload the final reflection to the LMS before 8 PM.',
    course: 'SE 318',
    estimatedPomodoros: 1,
    nextAction: 'Double-check citations and exported PDF before submission.',
    priority: 'High',
    status: 'Completed',
    dueDate: '2026-03-20T00:00:00.000Z',
  },
];
